version: '3.4'

services:
    cabinbookings:
        image: cabinbookings
        restart: unless-stopped
        volumes:
        - ./cabinbookings/data:/usr/src/app/data
        - ./cabinbookings/app.js:/usr/src/app/app.js
        build:
            context: ./cabinbookings
            dockerfile: ./Dockerfile
        ports:
            - 3011:3011
    cabinbookings-refresh:
        image: cabinbookings-refresh
        container_name: cabinbookings-refresh
        restart: "no"
        volumes:
        - ./cabinbookings-refresh/data:/usr/src/app/data
        - ./cabinbookings-refresh/util.js:/usr/src/app/util.js
        build:
            context: ./cabinbookings-refresh
            dockerfile: ./Dockerfile
    mariadb:
        # On 32bit rasbian docker host, you might need to run these:
        #   wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.4.4-1~bpo10+1_armhf.deb
        #   sudo dpkg -i libseccomp2_2.4.4-1~bpo10+1_armhf.deb
        image: linuxserver/mariadb:arm32v7-version-10.5.12-r0
        container_name: mariadb
        env_file:
        - ./mariadb/docker.env
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Helsinki
        volumes:
        - ./mariadb/config:/config
        restart: unless-stopped
    nginx:
        image: nginx
        restart: always
        ports:
        - 80:80
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    homeappnetapi:
        image: homeappnetapi
        restart: always
        env_file:
            - ./weatherapi/docker-env
        build:
            context: ./weatherapi
            dockerfile: ./Dockerfile
        ports:
            - 5000:5000
    calendarapi:
        env_file:
            - ./calendarapi/docker.env
        image: calendarapi
        restart: always
        build:
            context: ./calendarapi
            dockerfile: ./Dockerfile
        ports:
        - 5010:5010
    climateapi:
        image: climateapi
        restart: always
        build:
            context: ./climateapi
            dockerfile: ./Dockerfile
        volumes:
        - ./climateapi:/app
        ports:
        - 5011:5011
    homeapp73:
        image: homeapp73
        restart: always
        volumes:
        - ./homeclient/src:/usr/src/app/src
        - ./homeclient/public:/usr/src/app/public
        build:
            context: ./homeclient
            dockerfile: ./Dockerfile
        ports:
        - 3000:3000
    #airflow:
    #    image: airflow
    #    restart: always
    #    ports:
    #    - "8080:8080"
    #    volumes:
    #    - ./airflow/dags:/usr/local/airflow/dags
    #    build:
    #        context: ./airflow
    #        dockerfile: ./Dockerfile

    mosquitto:
        image: mosquitto
        build:
            context: ./mosquitto
            dockerfile: ./Dockerfile
        restart: always
#        volumes:
#            - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
        ports: 
            - "1883:1883"

    mqttclient:
        image: mqttclient
        restart: always
        volumes:
            - ./mqttclient:/usr/src/app
        build:
            context: ./mqttclient
            dockerfile: ./Dockerfile
    influxdb:
        image: influxdb
        container_name: influxdb
        restart: always
        ports:
            - 8086:8086
        volumes:
            - $PWD/influxdb:/var/lib/influxdb  
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:1.18.1
        volumes:
            - ./zigbee2mqtt:/app/data
            - /run/udev:/run/udev:ro
        devices:
            - /dev/ttyACM0:/dev/ttyACM0
        restart: always
        network_mode: host
        privileged: true
        environment:
            - TZ=Europe/Helsinki
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        restart: always
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
    grafana:
        container_name: grafana
        image: grafana/grafana
        restart: always
        ports:
            - 3010:3000 
            