version: '3.4'

services:
    homeappnetapi:
        image: homeappnetapi
        restart: always
        env_file:
            - ./weatherapi/docker-env
        build:
            context: ./weatherapi
            dockerfile: ./Dockerfile
        ports:
            - 5000:5000
    calendarapi:
        env_file:
            - ./calendarapi/docker.env
        image: calendarapi
        restart: always
        build:
            context: ./calendarapi
            dockerfile: ./Dockerfile
        ports:
        - 5010:5010
    climateapi:
        image: climateapi
        restart: always
        build:
            context: ./climateapi
            dockerfile: ./Dockerfile
        volumes:
        - ./climateapi:/app
        ports:
        - 5011:5011
    homeapp73:
        image: homeapp73
        restart: always
        volumes:
        - ./homeclient/src:/usr/src/app/src
        - ./homeclient/public:/usr/src/app/public
        build:
            context: ./homeclient
            dockerfile: ./Dockerfile
        ports:
        - 3000:3000
    airflow:
        image: airflow
        restart: always
        ports:
        - "8080:8080"
        volumes:
        - ./airflow/dags:/usr/local/airflow/dags
        build:
            context: ./airflow
            dockerfile: ./Dockerfile

    mosquitto:
        image: eclipse-mosquitto
        restart: always
        volumes:
            - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
        ports: 
            - "1883:1883"

    mqttclient:
        image: mqttclient
        restart: always
        volumes:
            - ./mqttclient:/usr/src/app
        build:
            context: ./mqttclient
            dockerfile: ./Dockerfile
    influxdb:
        image: influxdb
        container_name: influxdb
        restart: always
        ports:
            - 8086:8086
        volumes:
            - $PWD/influxdb:/var/lib/influxdb  
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        volumes:
            - ./zigbee2mqtt:/app/data
            - /run/udev:/run/udev:ro
        devices:
            - /dev/ttyACM0:/dev/ttyACM0
        restart: always
        network_mode: host
        privileged: true
        environment:
            - TZ=Europe/Helsinki
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        restart: always
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
    grafana:
        container_name: grafana
        image: grafana/grafana
        restart: always
        ports:
            - 3010:3000 
            