version: '3.4'

services:
    homeappnetapi:
        image: homeappnetapi
        env_file:
            - ./weatherapi/docker-env
        build:
            context: ./weatherapi
            dockerfile: ./Dockerfile
        ports:
            - 5000:5000
    calendarapi:
        env_file:
            - ./calendarapi/docker.env
        image: calendarapi
        build:
            context: ./calendarapi
            dockerfile: ./Dockerfile
        ports:
        - 5010:5010
    homeapp73:
        image: homeapp73
        build:
            context: ./homeclient
            dockerfile: ./Dockerfile
        ports:
        - 3000:3000
    airflow:
        image: airflow
        ports:
        - "8080:8080"
        volumes:
        - ./airflow/dags:/usr/local/airflow/dags
        build:
            context: ./airflow
            dockerfile: ./Dockerfile
        
            