global:
  scrape_interval:     15s
  evaluation_interval: 5s
  # scrape_timeout is set to the global default (10s).
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'docker'
    static_configs:
    - targets: ['172.17.0.1:9323']
  - job_name: 'raspberry'
    static_configs:
    - targets: ['172.17.0.1:9100']