apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 5s
      # scrape_timeout is set to the global default (10s).
    scrape_configs:
      - job_name: 'cadvisor'
        kubernetes_sd_configs:
        - role: node
      #        scheme: https
      #        tls_config:
      #          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #          insecure_skip_verify: true  # Required with Minikube.
        metrics_path: /metrics/cadvisor
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name
      - job_name: 'prometheus'
        static_configs:
        - targets: ['10.43.250.44:9090']
     # - job_name: 'docker'
     #   static_configs:
     #   - targets: ['172.17.0.1:9323']
      - job_name: 'raspberry'
        static_configs:
        - targets: ['192.168.10.217:9100']