apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: homeappnetapi
  name: homeappnetapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: homeappnetapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: homeappnetapi
    spec:
      containers:
        - image: localhost:5101/homeappnetapi
          name: homeappnetapi
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
