apiVersion: apps/v1
kind: Deployment
metadata:
  name: cabinbookings
spec:
  selector:
    matchLabels:
      app: cabinbookings
  template:
    metadata:
      labels:
        app: cabinbookings
    spec:
      containers:
      - env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              key: URL
              name: cabinbookings-docker-env
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              key: USERNAME
              name: cabinbookings-docker-env
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              key: PASSWORD
              name: cabinbookings-docker-env
        name: cabinbookings
        image: localhost:5101/cabinbookings
        resources: {}
        ports:
        - containerPort: 5020
