version: '3.4'

services:
   cabinbookings:
        image: cabinbookings
        container_name: cabinbookings
        restart: unless-stopped
        volumes:
        - ./app.js:/usr/src/app/app.js
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 3011:3011
