version: '3.4'

services:
  airflow:
    image: airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
    build:
      context: .
      dockerfile: ./Dockerfile
