version: '3.4'

services:
  homeapp73:
    image: homeapp73
    volumes:
      - $(pwd):/usr/src/app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  