apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: zigbee2mqtt
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: zigbee2mqtt
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Helsinki
          image: koenkk/zigbee2mqtt
          name: zigbee2mqtt
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /app/data
              name: zigbee2mqtt-claim0
            - mountPath: /run/udev
              name: zigbee2mqtt-claim1
              readOnly: true
            - mountPath: /dev/ttyACM0
              name: zigbee2mqtt-claim-claim2
      restartPolicy: Always
      volumes:
        - name: zigbee2mqtt-claim0
          persistentVolumeClaim:
            claimName: zigbee2mqtt-claim0
        - name: zigbee2mqtt-claim1
          persistentVolumeClaim:
            claimName: zigbee2mqtt-claim1
            readOnly: true
        - name: zigbee2mqtt-claim-claim2
          hostPath:
            path: /dev/ttyACM0

status: {}
