version: '3.4'

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    network_mode: container:influxdb
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro 
