apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: calendarapi
  name: calendarapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: calendarapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: calendarapi
    spec:
      containers:
        - env:
            - name: CALENDAR_URL
              valueFrom:
                configMapKeyRef:
                  key: CALENDAR_URL
                  name: calendarapi-docker-env
            - name: CAL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CAL_PASSWORD
                  name: calendarapi-docker-env
            - name: CAL_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: CAL_USERNAME
                  name: calendarapi-docker-env
          image: localhost:5101/calendarapi
          name: calendarapi
          ports:
            - containerPort: 5010
          resources: {}
      restartPolicy: Always
status: {}
