version: '3.4'

services:
  calendarapi:
    env_file:
      - ./docker.env
    image: calendarapi
    build:
      context: .
      dockerfile: ./Dockerfile.alpine
    ports:
      - 5010:5010
